[package]
name = "c_to_f"
version = "0.1.0"
authors = ["Danny Lowater <dannylow456@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
